export const GET_ADDRESSTYPE_REQUEST = 'GET_ADDRESSTYPE_REQUEST'
export const GET_ADDRESSTYPE_SUCCESS = 'GET_ADDRESSTYPE_SUCCESS'
export const GET_ADDRESSTYPE_FAILED = 'GET_ADDRESSTYPE_FAILED'

export const DEL_ADDRESSTYPE_REQUEST = 'DEL_ADDRESSTYPE_REQUEST'
export const DEL_ADDRESSTYPE_SUCCESS = 'DEL_ADDRESSTYPE_SUCCESS'
export const DEL_ADDRESSTYPE_FAILED = 'DEL_ADDRESSTYPE_FAILED'

export const ADD_ADDRESSTYPE_REQUEST = 'ADD_ADDRESSTYPE_REQUEST'
export const ADD_ADDRESSTYPE_SUCCESS = 'ADD_ADDRESSTYPE_SUCCESS'
export const ADD_ADDRESSTYPE_FAILED = 'ADD_ADDRESSTYPE_FAILED'

export const GETONE_ADDRESSTYPE_REQUEST = 'GETONE_ADDRESSTYPE_REQUEST'
export const GETONE_ADDRESSTYPE_SUCCESS = 'GETONE_ADDRESSTYPE_SUCCESS'
export const GETONE_ADDRESSTYPE_FAILED = 'GETONE_ADDRESSTYPE_FAILED'

export const EDIT_ADDRESSTYPE_REQUEST = 'EDIT_ADDRESSTYPE_REQUEST'
export const EDIT_ADDRESSTYPE_SUCCESS = 'EDIT_ADDRESSTYPE_SUCCESS'
export const EDIT_ADDRESSTYPE_FAILED = 'EDIT_ADDRESSTYPE_FAILED'
