export const GET_BOOTCAMPPROGRAM_REQUEST = 'GET_BOOTCAMPPROGRAM_REQUEST';
export const GET_BOOTCAMPPROGRAM_SUCCEED = 'GET_BOOTCAMPPROGRAM_SUCCEED';
export const GET_BOOTCAMPPROGRAM_FAILED = 'GET_BOOTCAMPPROGRAM_FAILED';

export const GET_SEARCHPROGRAM_REQUEST = 'GET_SEARCHPROGRAM_REQUEST';
export const GET_SEARCHPROGRAM_SUCCEED = 'GET_SEARCHPROGRAM_SUCCEED';
export const GET_SEARCHPROGRAM_FAILED = 'GET_SEARCHPROGRAM_FAILED';