export const GET_BOOTCAMP_REQUEST = "GET_BOOTCAMP_REQUEST";
export const GET_BOOTCAMP_SUCCEED = "GET_BOOTCAMP_SUCCEED";
export const GET_BOOTCAMP_FAILED = "GET_BOOTCAMP_FAILED";

export const APPLY_BOOTCAMP_REQUEST = "APPLY_BOOTCAMP_REQUEST";
export const APPLY_BOOTCAMP_SUCCEED = "APPLY_BOOTCAMP_SUCCEED";
export const APPLY_BOOTCAMP_FAILED = "APPLY_BOOTCAMP_FAILED";

export const RESET_APPLY_BOOTCAMP_REQUEST = "RESET_APPLY_BOOTCAMP_REQUEST";
export const RESET_APPLY_BOOTCAMP_SUCCEED = "RESET_APPLY_BOOTCAMP_SUCCEED";
export const RESET_APPLY_BOOTCAMP_FAILED = "RESET_APPLY_BOOTCAMP_FAILED";