export const GET_CITY_REQUEST = 'GET_CITY_REQUEST'
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS'
export const GET_CITY_FAILED = 'GET_CITY_FAILED'

export const DEL_CITY_REQUEST = 'DEL_CITY_REQUEST'
export const DEL_CITY_SUCCESS = 'DEL_CITY_SUCCESS'
export const DEL_CITY_FAILED = 'DEL_CITY_FAILED'

export const ADD_CITY_REQUEST = 'ADD_CITY_REQUEST'
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS'
export const ADD_CITY_FAILED = 'ADD_CITY_FAILED'

export const GETONE_CITY_REQUEST = 'GETONE_CITY_REQUEST'
export const GETONE_CITY_SUCCESS = 'GETONE_CITY_SUCCESS'
export const GETONE_CITY_FAILED = 'GETONE_CITY_FAILED'

export const EDIT_CITY_REQUEST = 'EDIT_CITY_REQUEST'
export const EDIT_CITY_SUCCESS = 'EDIT_CITY_SUCCESS'
export const EDIT_CITY_FAILED = 'EDIT_CITY_FAILED'
