export const GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST'
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS'
export const GET_COUNTRY_FAILED = 'GET_COUNTRY_FAILED'

export const DEL_COUNTRY_REQUEST = 'DEL_COUNTRY_REQUEST'
export const DEL_COUNTRY_SUCCESS = 'DEL_COUNTRY_SUCCESS'
export const DEL_COUNTRY_FAILED = 'DEL_COUNTRY_FAILED'

export const ADD_COUNTRY_REQUEST = 'ADD_COUNTRY_REQUEST'
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS'
export const ADD_COUNTRY_FAILED = 'ADD_COUNTRY_FAILED'

export const GETONE_COUNTRY_REQUEST = 'GETONE_COUNTRY_REQUEST'
export const GETONE_COUNTRY_SUCCESS = 'GETONE_COUNTRY_SUCCESS'
export const GETONE_COUNTRY_FAILED = 'GETONE_COUNTRY_FAILED'

export const EDIT_COUNTRY_REQUEST = 'EDIT_COUNTRY_REQUEST'
export const EDIT_COUNTRY_SUCCESS = 'EDIT_COUNTRY_SUCCESS'
export const EDIT_COUNTRY_FAILED = 'EDIT_COUNTRY_FAILED'
