export const GET_ADDRESSTYPE_REQUEST = 'GET_ADDRESSTYPE_REQUEST'
export const GET_ADDRESSTYPE_SUCCESS = 'GET_ADDRESSTYPE_SUCCESS'
export const GET_ADDRESSTYPE_FAILED = 'GET_ADDRESSTYPE_FAILED'

export const DEL_ADDRESSTYPE_REQUEST = 'DEL_ADDRESSTYPE_REQUEST'
export const DEL_ADDRESSTYPE_SUCCESS = 'DEL_ADDRESSTYPE_SUCCESS'
export const DEL_ADDRESSTYPE_FAILED = 'DEL_ADDRESSTYPE_FAILED'

export const ADD_ADDRESSTYPE_REQUEST = 'ADD_ADDRESSTYPE_REQUEST'
export const ADD_ADDRESSTYPE_SUCCESS = 'ADD_ADDRESSTYPE_SUCCESS'
export const ADD_ADDRESSTYPE_FAILED = 'ADD_ADDRESSTYPE_FAILED'

export const GETONE_ADDRESSTYPE_REQUEST = 'GETONE_ADDRESSTYPE_REQUEST'
export const GETONE_ADDRESSTYPE_SUCCESS = 'GETONE_ADDRESSTYPE_SUCCESS'
export const GETONE_ADDRESSTYPE_FAILED = 'GETONE_ADDRESSTYPE_FAILED'

export const EDIT_ADDRESSTYPE_REQUEST = 'EDIT_ADDRESSTYPE_REQUEST'
export const EDIT_ADDRESSTYPE_SUCCESS = 'EDIT_ADDRESSTYPE_SUCCESS'
export const EDIT_ADDRESSTYPE_FAILED = 'EDIT_ADDRESSTYPE_FAILED'

export const GET_COUNTRY_REQUEST = 'GET_COUNTRY_REQUEST'
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS'
export const GET_COUNTRY_FAILED = 'GET_COUNTRY_FAILED'

export const DEL_COUNTRY_REQUEST = 'DEL_COUNTRY_REQUEST'
export const DEL_COUNTRY_SUCCESS = 'DEL_COUNTRY_SUCCESS'
export const DEL_COUNTRY_FAILED = 'DEL_COUNTRY_FAILED'

export const ADD_COUNTRY_REQUEST = 'ADD_COUNTRY_REQUEST'
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS'
export const ADD_COUNTRY_FAILED = 'ADD_COUNTRY_FAILED'

export const GETONE_COUNTRY_REQUEST = 'GETONE_COUNTRY_REQUEST'
export const GETONE_COUNTRY_SUCCESS = 'GETONE_COUNTRY_SUCCESS'
export const GETONE_COUNTRY_FAILED = 'GETONE_COUNTRY_FAILED'

export const EDIT_COUNTRY_REQUEST = 'EDIT_COUNTRY_REQUEST'
export const EDIT_COUNTRY_SUCCESS = 'EDIT_COUNTRY_SUCCESS'
export const EDIT_COUNTRY_FAILED = 'EDIT_COUNTRY_FAILED'

export const GET_PROVINCE_REQUEST = 'GET_PROVINCE_REQUEST'
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS'
export const GET_PROVINCE_FAILED = 'GET_PROVINCE_FAILED'

export const DEL_PROVINCE_REQUEST = 'DEL_PROVINCE_REQUEST'
export const DEL_PROVINCE_SUCCESS = 'DEL_PROVINCE_SUCCESS'
export const DEL_PROVINCE_FAILED = 'DEL_PROVINCE_FAILED'

export const ADD_PROVINCE_REQUEST = 'ADD_PROVINCE_REQUEST'
export const ADD_PROVINCE_SUCCESS = 'ADD_PROVINCE_SUCCESS'
export const ADD_PROVINCE_FAILED = 'ADD_PROVINCE_FAILED'

export const GETONE_PROVINCE_REQUEST = 'GETONE_PROVINCE_REQUEST'
export const GETONE_PROVINCE_SUCCESS = 'GETONE_PROVINCE_SUCCESS'
export const GETONE_PROVINCE_FAILED = 'GETONE_PROVINCE_FAILED'

export const EDIT_PROVINCE_REQUEST = 'EDIT_PROVINCE_REQUEST'
export const EDIT_PROVINCE_SUCCESS = 'EDIT_PROVINCE_SUCCESS'
export const EDIT_PROVINCE_FAILED = 'EDIT_PROVINCE_FAILED'

export const GET_CITY_REQUEST = 'GET_CITY_REQUEST'
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS'
export const GET_CITY_FAILED = 'GET_CITY_FAILED'

export const DEL_CITY_REQUEST = 'DEL_CITY_REQUEST'
export const DEL_CITY_SUCCESS = 'DEL_CITY_SUCCESS'
export const DEL_CITY_FAILED = 'DEL_CITY_FAILED'

export const ADD_CITY_REQUEST = 'ADD_CITY_REQUEST'
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS'
export const ADD_CITY_FAILED = 'ADD_CITY_FAILED'

export const GETONE_CITY_REQUEST = 'GETONE_CITY_REQUEST'
export const GETONE_CITY_SUCCESS = 'GETONE_CITY_SUCCESS'
export const GETONE_CITY_FAILED = 'GETONE_CITY_FAILED'

export const EDIT_CITY_REQUEST = 'EDIT_CITY_REQUEST'
export const EDIT_CITY_SUCCESS = 'EDIT_CITY_SUCCESS'
export const EDIT_CITY_FAILED = 'EDIT_CITY_FAILED'
