export const GET_MODULESMASTER_MODULES_REQUEST =
  "GET_MODULESMASTER_MODULES_REQUEST";
export const GET_MODULESMASTER_MODULES_SUCCESS =
  "GET_MODULESMASTER_MODULES_SUCCESS";
export const GET_MODULESMASTER_MODULES_FAILED =
  "GET_MODULESMASTER_MODULES_FAILED";

export const GET_MODULESMASTER_ROUTEACTIONS_REQUEST =
  "GET_MODULESMASTER_ROUTEACTIONS_REQUEST";
export const GET_MODULESMASTER_ROUTEACTIONS_SUCCESS =
  "GET_MODULESMASTER_ROUTEACTIONS_SUCCESS";
export const GET_MODULESMASTER_ROUTEACTIONS_FAILED =
  "GET_MODULESMASTER_ROUTEACTIONS_FAILED";

// export const DEL_MODULES_REQUEST = "DEL_MODULES_REQUEST";
// export const DEL_MODULES_SUCCESS = "DEL_MODULES_SUCCESS";
// export const DEL_MODULES_FAILED = "DEL_MODULES_FAILED";

// export const ADD_MODULES_REQUEST = "ADD_MODULES_REQUEST";
// export const ADD_MODULES_SUCCESS = "ADD_MODULES_SUCCESS";
// export const ADD_MODULES_FAILED = "ADD_MODULES_FAILED";

// export const EDIT_MODULES_REQUEST = "EDIT_MODULES_REQUEST";
// export const EDIT_MODULES_SUCCESS = "EDIT_MODULES_SUCCESS";
// export const EDIT_MODULES_FAILED = "EDIT_MODULES_FAILED";
