export const GETFOUR_PROGRAM_REQUEST = 'GETFOUR_PROGRAM_REQUEST'
export const GETFOUR_PROGRAM_SUCCESS = 'GETFOUR_PROGRAM_SUCCESS'
export const GETFOUR_PROGRAM_FAILED = 'GETFOUR_PROGRAM_FAILED'

export const GETTHREE_COURSE_REQUEST = 'GETTHREE_COURSE_REQUEST'
export const GETTHREE_COURSE_SUCCESS = 'GETTHREE_COURSE_SUCCESS'
export const GETTHREE_COURSE_FAILED = 'GETTHREE_COURSE_FAILED'

export const GETALUMNI_TESTIMONY_REQUEST = 'GETALUMNI_TESTIMONY_REQUEST'
export const GETALUMNI_TESTIMONY_SUCCESS = 'GETALUMNI_TESTIMONY_SUCCESS'
export const GETALUMNI_TESTIMONY_FAILED = 'GETALUMNI_TESTIMONY_FAILED'