export const GET_PROVINCE_REQUEST = 'GET_PROVINCE_REQUEST'
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS'
export const GET_PROVINCE_FAILED = 'GET_PROVINCE_FAILED'

export const DEL_PROVINCE_REQUEST = 'DEL_PROVINCE_REQUEST'
export const DEL_PROVINCE_SUCCESS = 'DEL_PROVINCE_SUCCESS'
export const DEL_PROVINCE_FAILED = 'DEL_PROVINCE_FAILED'

export const ADD_PROVINCE_REQUEST = 'ADD_PROVINCE_REQUEST'
export const ADD_PROVINCE_SUCCESS = 'ADD_PROVINCE_SUCCESS'
export const ADD_PROVINCE_FAILED = 'ADD_PROVINCE_FAILED'

export const GETONE_PROVINCE_REQUEST = 'GETONE_PROVINCE_REQUEST'
export const GETONE_PROVINCE_SUCCESS = 'GETONE_PROVINCE_SUCCESS'
export const GETONE_PROVINCE_FAILED = 'GETONE_PROVINCE_FAILED'

export const EDIT_PROVINCE_REQUEST = 'EDIT_PROVINCE_REQUEST'
export const EDIT_PROVINCE_SUCCESS = 'EDIT_PROVINCE_SUCCESS'
export const EDIT_PROVINCE_FAILED = 'EDIT_PROVINCE_FAILED'
