export const GET_ROUTEACTIONS_REQUEST = "GET_ROUTEACTIONS_REQUEST";
export const GET_ROUTEACTIONS_SUCCESS = "GET_ROUTEACTIONS_SUCCESS";
export const GET_ROUTEACTIONS_FAILED = "GET_ROUTEACTIONS_FAILED";

export const GETONE_ROUTEACTIONS_REQUEST = "GETONE_ROUTEACTIONS_REQUEST";
export const GETONE_ROUTEACTIONS_SUCCESS = "GETONE_ROUTEACTIONS_SUCCESS";
export const GETONE_ROUTEACTIONS_FAILED = "GETONE_ROUTEACTIONS_FAILED";

export const DEL_ROUTEACTIONS_REQUEST = "DEL_ROUTEACTIONS_REQUEST";
export const DEL_ROUTEACTIONS_SUCCESS = "DEL_ROUTEACTIONS_SUCCESS";
export const DEL_ROUTEACTIONS_FAILED = "DEL_ROUTEACTIONS_FAILED";

export const ADD_ROUTEACTIONS_REQUEST = "ADD_ROUTEACTIONS_REQUEST";
export const ADD_ROUTEACTIONS_SUCCESS = "ADD_ROUTEACTIONS_SUCCESS";
export const ADD_ROUTEACTIONS_FAILED = "ADD_ROUTEACTIONS_FAILED";

export const EDIT_ROUTEACTIONS_REQUEST = "EDIT_ROUTEACTIONS_REQUEST";
export const EDIT_ROUTEACTIONS_SUCCESS = "EDIT_ROUTEACTIONS_SUCCESS";
export const EDIT_ROUTEACTIONS_FAILED = "EDIT_ROUTEACTIONS_FAILED";
