export const GET_STUDENTREVIEW_REQUEST = 'GET_STUDENTREVIEW_REQUEST';
export const GET_STUDENTREVIEW_SUCCEED = 'GET_STUDENTREVIEW_SUCCEED';
export const GET_STUDENTREVIEW_FAILED = 'GET_STUDENTREVIEW_FAILED';